var searchData=
[
  ['callback_20registration_1861',['Callback registration',['../group__autogenerated.html',1,'']]],
  ['callbacks_1862',['Callbacks',['../group__callbacks.html',1,'']]],
  ['communication_20with_20the_20module_1863',['Communication with the module',['../group__communication.html',1,'']]],
  ['configuration_20options_1864',['Configuration options',['../group__configuration.html',1,'']]],
  ['controlling_20the_20module_1865',['Controlling the module',['../group__modulecontrol.html',1,'']]]
];
