var annotated_dup =
[
    [ "ucxhAT_ipV6GenericAddrStr_t", "structucxh_a_t__ip_v6_generic_addr_str__t.html", "structucxh_a_t__ip_v6_generic_addr_str__t" ],
    [ "ucxhEDM_atEvent_t", "structucxh_e_d_m__at_event__t.html", "structucxh_e_d_m__at_event__t" ],
    [ "ucxhEDM_connectionEventBT_t", "structucxh_e_d_m__connection_event_b_t__t.html", "structucxh_e_d_m__connection_event_b_t__t" ],
    [ "ucxhEDM_connectionEventIPv4_t", "structucxh_e_d_m__connection_event_i_pv4__t.html", "structucxh_e_d_m__connection_event_i_pv4__t" ],
    [ "ucxhEDM_connectionEventIPv6_t", "structucxh_e_d_m__connection_event_i_pv6__t.html", "structucxh_e_d_m__connection_event_i_pv6__t" ],
    [ "ucxhEDM_dataEvent_t", "structucxh_e_d_m__data_event__t.html", "structucxh_e_d_m__data_event__t" ],
    [ "ucxhEDM_disconnectEvent_t", "structucxh_e_d_m__disconnect_event__t.html", "structucxh_e_d_m__disconnect_event__t" ],
    [ "ucxhEDM_event_t", "structucxh_e_d_m__event__t.html", "structucxh_e_d_m__event__t" ],
    [ "ucxhPARSER_defaultRemotePeerParam_t", "structucxh_p_a_r_s_e_r__default_remote_peer_param__t.html", "structucxh_p_a_r_s_e_r__default_remote_peer_param__t" ],
    [ "ucxhPARSER_peerURL_t", "structucxh_p_a_r_s_e_r__peer_u_r_l__t.html", "structucxh_p_a_r_s_e_r__peer_u_r_l__t" ],
    [ "ucxhPARSER_urcConnectPeerEvent_t", "structucxh_p_a_r_s_e_r__urc_connect_peer_event__t.html", "structucxh_p_a_r_s_e_r__urc_connect_peer_event__t" ],
    [ "ucxhPARSER_urcIdentificationInformationEvent_t", "structucxh_p_a_r_s_e_r__urc_identification_information_event__t.html", "structucxh_p_a_r_s_e_r__urc_identification_information_event__t" ],
    [ "ucxhPARSER_urcLocalAddressEvent_t", "structucxh_p_a_r_s_e_r__urc_local_address_event__t.html", "structucxh_p_a_r_s_e_r__urc_local_address_event__t" ],
    [ "ucxhPARSER_urcManufacturerIdentificationEvent_t", "structucxh_p_a_r_s_e_r__urc_manufacturer_identification_event__t.html", "structucxh_p_a_r_s_e_r__urc_manufacturer_identification_event__t" ],
    [ "ucxhPARSER_urcMcuIdentificationEvent_t", "structucxh_p_a_r_s_e_r__urc_mcu_identification_event__t.html", "structucxh_p_a_r_s_e_r__urc_mcu_identification_event__t" ],
    [ "ucxhPARSER_urcModelIdentificationEvent_t", "structucxh_p_a_r_s_e_r__urc_model_identification_event__t.html", "structucxh_p_a_r_s_e_r__urc_model_identification_event__t" ],
    [ "ucxhPARSER_urcNetworkDownEvent_t", "structucxh_p_a_r_s_e_r__urc_network_down_event__t.html", "structucxh_p_a_r_s_e_r__urc_network_down_event__t" ],
    [ "ucxhPARSER_urcNetworkStatusEvent_t", "structucxh_p_a_r_s_e_r__urc_network_status_event__t.html", "structucxh_p_a_r_s_e_r__urc_network_status_event__t" ],
    [ "ucxhPARSER_urcNetworkUpEvent_t", "structucxh_p_a_r_s_e_r__urc_network_up_event__t.html", "structucxh_p_a_r_s_e_r__urc_network_up_event__t" ],
    [ "ucxhPARSER_urcPeerConnectedEvent_t", "structucxh_p_a_r_s_e_r__urc_peer_connected_event__t.html", "structucxh_p_a_r_s_e_r__urc_peer_connected_event__t" ],
    [ "ucxhPARSER_urcPeerDisconnectedEvent_t", "structucxh_p_a_r_s_e_r__urc_peer_disconnected_event__t.html", "structucxh_p_a_r_s_e_r__urc_peer_disconnected_event__t" ],
    [ "ucxhPARSER_urcSerialNumberEvent_t", "structucxh_p_a_r_s_e_r__urc_serial_number_event__t.html", "structucxh_p_a_r_s_e_r__urc_serial_number_event__t" ],
    [ "ucxhPARSER_urcSoftwareVersionIdentificationEvent_t", "structucxh_p_a_r_s_e_r__urc_software_version_identification_event__t.html", "structucxh_p_a_r_s_e_r__urc_software_version_identification_event__t" ],
    [ "ucxhPARSER_urcStartupEvent_t", "structucxh_p_a_r_s_e_r__urc_startup_event__t.html", "structucxh_p_a_r_s_e_r__urc_startup_event__t" ],
    [ "ucxhPARSER_urcTypeCodeIdentificationEvent_t", "structucxh_p_a_r_s_e_r__urc_type_code_identification_event__t.html", "structucxh_p_a_r_s_e_r__urc_type_code_identification_event__t" ],
    [ "ucxhPARSER_urcWifiLinkConnectedEvent_t", "structucxh_p_a_r_s_e_r__urc_wifi_link_connected_event__t.html", "structucxh_p_a_r_s_e_r__urc_wifi_link_connected_event__t" ],
    [ "ucxhPARSER_urcWifiLinkDisconnectedEvent_t", "structucxh_p_a_r_s_e_r__urc_wifi_link_disconnected_event__t.html", "structucxh_p_a_r_s_e_r__urc_wifi_link_disconnected_event__t" ],
    [ "ucxhPARSER_urcWifiStationConfigurationEvent_t", "structucxh_p_a_r_s_e_r__urc_wifi_station_configuration_event__t.html", null ],
    [ "ucxhPARSER_urcWifiStationStatusEvent_t", "structucxh_p_a_r_s_e_r__urc_wifi_station_status_event__t.html", "structucxh_p_a_r_s_e_r__urc_wifi_station_status_event__t" ],
    [ "ucxhPARSER_urcXXXEvent_t", "structucxh_p_a_r_s_e_r__urc_x_x_x_event__t.html", "structucxh_p_a_r_s_e_r__urc_x_x_x_event__t" ],
    [ "ucxhPARSER_wifiStationConfiguration_t", "structucxh_p_a_r_s_e_r__wifi_station_configuration__t.html", "structucxh_p_a_r_s_e_r__wifi_station_configuration__t" ],
    [ "ucxhPARSER_wifiStationConfigurationParam_t", "structucxh_p_a_r_s_e_r__wifi_station_configuration_param__t.html", "structucxh_p_a_r_s_e_r__wifi_station_configuration_param__t" ]
];