var group__callbacks =
[
    [ "Module Callbacks", "group__modulecallbacks.html", "group__modulecallbacks" ],
    [ "EDM Callbacks", "group__edmcallbacks.html", "group__edmcallbacks" ],
    [ "Parser callbacks", "group__parsercallbacks.html", "group__parsercallbacks" ],
    [ "URC Callbacks", "group__urccallbacks.html", "group__urccallbacks" ],
    [ "Callback registration", "group__autogenerated.html", "group__autogenerated" ]
];