/*
@licstart  The following is the entire license notice for the
JavaScript code in this file.

Copyright (C) 1997-2019 by Dimitri van Heesch

This program is free software; you can redistribute it and/or modify
it under the terms of version 2 of the GNU General Public License as published by
the Free Software Foundation

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

@licend  The above is the entire license notice
for the JavaScript code in this file
*/
var NAVTREE =
[
  [ "u-connectXpress host library", "index.html", [
    [ "Introduction", "index.html", [
      [ "Usage", "index.html#autotoc_md1", [
        [ "Running your first example on CygWin", "index.html#autotoc_md2", null ],
        [ "Running the second examples on CygWin", "index.html#autotoc_md3", null ],
        [ "Using the AT command library with your host application", "index.html#autotoc_md4", null ]
      ] ],
      [ "Documentation", "index.html#autotoc_md5", null ],
      [ "Examples", "index.html#autotoc_md6", [
        [ "ex_readmisc", "index.html#autotoc_md7", null ],
        [ "ex_callbacks_edm_wifi", "index.html#autotoc_md8", null ]
      ] ],
      [ "Porting", "index.html#autotoc_md9", null ],
      [ "Testing", "index.html#autotoc_md10", [
        [ "Unit-tests", "index.html#autotoc_md11", [
          [ "test_getgeneral", "index.html#autotoc_md12", null ],
          [ "test_getsystem", "index.html#autotoc_md13", null ],
          [ "test_at_wifi", "index.html#autotoc_md14", null ],
          [ "test_tokenizer", "index.html#autotoc_md15", null ],
          [ "test_send", "index.html#autotoc_md16", null ],
          [ "test_mock_ati9", "index.html#autotoc_md17", null ]
        ] ],
        [ "Manual test", "index.html#autotoc_md18", [
          [ "test_ati9", "index.html#autotoc_md19", null ],
          [ "test_datamode", "index.html#autotoc_md20", null ],
          [ "test_edm_at", "index.html#autotoc_md21", null ],
          [ "test_edm_at_read", "index.html#autotoc_md22", null ]
        ] ]
      ] ],
      [ "Using runExamples.sh", "index.html#autotoc_md23", null ],
      [ "Disclaimer", "index.html#autotoc_md24", null ]
    ] ],
    [ "Test List", "test.html", null ],
    [ "Bug List", "bug.html", null ],
    [ "Detailed documentation", "modules.html", "modules" ],
    [ "Data Structures", "annotated.html", [
      [ "Data Structures", "annotated.html", "annotated_dup" ],
      [ "Data Structure Index", "classes.html", null ],
      [ "Data Fields", "functions.html", [
        [ "All", "functions.html", null ],
        [ "Variables", "functions_vars.html", null ]
      ] ]
    ] ],
    [ "Files", "files.html", [
      [ "File List", "files.html", "files_dup" ],
      [ "Globals", "globals.html", [
        [ "All", "globals.html", "globals_dup" ],
        [ "Functions", "globals_func.html", "globals_func" ],
        [ "Variables", "globals_vars.html", null ],
        [ "Typedefs", "globals_type.html", null ],
        [ "Enumerations", "globals_enum.html", null ],
        [ "Enumerator", "globals_eval.html", null ],
        [ "Macros", "globals_defs.html", "globals_defs" ]
      ] ]
    ] ],
    [ "Examples", "examples.html", "examples" ]
  ] ]
];

var NAVTREEINDEX =
[
"annotated.html",
"group__autogenerated.html",
"group__modulecontrol.html#ga77d532f4b3b0676e305c33933129969a",
"index.html",
"test__datamode_8c.html#a9987186d87280b116b222595fb175c86",
"ucxh__serial__mock_8c.html#aebbf878d4b4d2bfb2e06b90eeb86b51b"
];

var SYNCONMSG = 'click to disable panel synchronisation';
var SYNCOFFMSG = 'click to enable panel synchronisation';